package nl.remcoblom.bitvavoviewer;

public enum Currency {
    EUR, AE, ADA, AION, ANT, ARK, BAT, BCH, BSV, BTC, CMT, DCR, DGB, ELF,
    ENJ, EOS, ETH, ETC, GNT, HOT, ICX, IOST, KMD, LINK, LSK, LRC, LTC, MIOTA,
    NANO, NAS, NEO, GAS, NULS, NPXS, OMG, ONT, ONG, POWR, QTUM, RVN,
    REQ, RDD, SNT, STEEM, STORM, STRAT, TRX, VET, VTHO, VTC, WAVES, WTC, XEM, XVG, XRP, XLM, XTZ, ZIL, ZRX;
}
